import React from 'react';
import {StyleSheet, Dimensions} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
const height = Dimensions.get('window').height;
const styles = StyleSheet.create({
  mainView: {
    flex: 1,
    backgroundColor: 'white',
  },
  secondView: {
    flex: 1,
    alignItems: 'center',
    // backgroundColor: 'red',
    //   justifyContent:"center",
  },
  thirdView: {
    flex: 2,
    alignItems: 'center',
    //   justifyContent:"center",
  },
  bottom: {
    marginTop: 20,
    width: '100%',
    alignItems: 'center',
  },
  image: {
    height: 100,
    width: 100,
    marginTop: 30,
  },
  red0: {color: '#FF4029', fontFamily: 'Nunito-Regular'},
  red: {color: 'black', fontFamily: 'Nunito-Bold'},
  red1: {
    color: 'black',
    marginTop: 5,
    fontSize: 16,
    fontFamily: 'Nunito-SemiBold',
  },
  white: {color: 'white', fontSize: 18, fontFamily: 'Nunito-SemiBold'},
  login: {fontSize: 20, color: 'black', fontFamily: 'Nunito-Bold'},
  inputView: {
    backgroundColor: 'white',
    elevation: 4,
    height: 50,
    width: '90%',
    marginTop: 20,
    borderRadius: 10,
  },
  placeholder: {
    marginLeft: 15,
    // backgroundColor: 'red',
    height: '100%',
    fontFamily: 'Nunito-Regular',
    fontSize: 16,
    color: 'black',
  },
  forgot: {
    marginTop: 10,
    width: '90%',

    alignItems: 'flex-end',
  },
  loginButton: {
    height: 50,
    backgroundColor: 'black',
    width: '90%',
    marginTop: 100,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
  },
  signUpView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  modalView: {
    flex: 1,
    backgroundColor: '#00000088',
    justifyContent: 'flex-end',
  },
  forgotView: {
    backgroundColor: 'white',
    height: '55%',
    borderTopLeftRadius: 25,
    paddingHorizontal: 20,
    borderTopRightRadius: 25,
    width: '100%',
  },
  left: {
    marginLeft: 20,
    color: 'black',
    fontSize: 18,
    fontFamily: 'Nunito-Bold',
  },
  topView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  normalText: {
    marginTop: 20,
    fontSize: 16,
    color: 'black',
    fontFamily: 'Nunito-SemiBold',
    // backgroundColor: 'red',
  },
  empty: {height: 10},
  enterMail: {
    flex: 1,
    marginTop: 20,
    // backgroundColor: 'blue',
    // justifyContent: 'center',
  },
  mail: {
    backgroundColor: 'white',
    elevation: 4,
    borderRadius: 10,
    // marginTop: 10,
    height: 50,
  },
  input: {
    paddingLeft: 15,
    color: 'black',
    fontSize: 16,
    height: '100%',
    fontFamily: 'Nunito-Regular',
  },

  sendEmail: {
    height: 50,
    width: '100%',
    backgroundColor: 'black',
    alignItems: 'center',
    // marginTop: 0,
    // marginBottom: 10,
    justifyContent: 'center',
    borderRadius: 30,
    position: 'absolute',
    bottom: 10,
  },
  sendEmail1: {
    height: 50,
    width: '100%',
    position: 'absolute',
    bottom: 10,
    backgroundColor: 'black',
    alignItems: 'center',
    marginLeft: 15,
    marginTop: hp(10),
    // marginBottom: 10,
    justifyContent: 'center',
    borderRadius: 30,
  },
  root: {flex: 1, padding: 0},
  title: {textAlign: 'center', fontSize: 30},
  codeFieldRoot: {marginTop: 0},
  cell: {
    width: 40,
    height: 40,
    lineHeight: 38,
    // backgroundColor: 'red',
    color: 'black',
    marginHorizontal: 20,
    fontSize: 20,
    fontFamily: 'Nunito-SemiBold',
    // borderWidth: 2,
    marginTop: 20,
    borderColor: 'white',
    backgroundColor: 'white',
    elevation: 4,
    textAlign: 'center',
  },
  focusCell: {
    borderColor: 'white',
  },
});
export default styles;
